name: check-pr
on:
  pull_request:
    branches:
      - master    
      - develop
    types: ['opened', 'reopened', 'synchronize']
  

permissions: write-all
   
jobs:
  check-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: |
          echo PR labeled in ${{ github.event.pull_request.base.ref }}
          echo testing
      - name: test add label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['label']
            })          
