name: 1. Run Test
on:
  workflow_dispatch:
  ## LIMIT OF 10 INPUTS
    inputs:
      text:
        type: string
        description: type any string
        required: false
env:
  NAME: ${{ format('{0:yyyy-MM-dd}', github.event.workflow_run.created_at) }}
  
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Print
        run: echo $NAME

  
