name: 1. Run Test
on:
  workflow_dispatch:
  ## LIMIT OF 10 INPUTS
    inputs:
      text:
        type: string
        description: type any string
        required: false
env:
  NAME: test-${{ inputs.text }}-${{ github.event.workflow_dispatch.created_at }}
  
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Print
        run: echo $NAME

  
