name: 1. Run Test
on:
  workflow_dispatch:
  ## LIMIT OF 10 INPUTS
    inputs:
      text:
        type: string
        description: type any string
        required: false
env:
  NAME: test-${{ inputs.text }}
  
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Format
        run: echo "DEPLOY_BRANCH=${env.name}-$(date +'%Y-%m-%d')-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Print
        run: echo $DEPLOY_BRANCH


  
